collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist

# Custom vars
github: https://github.com/CEGRcode
twitter: https://twitter.com/ThePughLab

# google analytics
google_analytics: UA-104503525-2
